export { default as Home } from './home/Home';
export { default as Category } from './category/Category';
export { default as Signin } from './signin/Signin';
export { default as Footer } from './layout/Footer';
export { default as Navbar } from './layout/Navbar';
export { default as Signout } from './layout/SignOut';
export { default as DashBoard } from './dashboard/DashBoard';
export { default as Type } from './type/Type';
export { default as Product } from './product/Product';
