export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
